version: '2'
services:
  db:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      - db
    expose:
      - 5000
    ports:
      - 5000:5000
    restart: unless-stopped
